### ISSUE TITLE
逻辑错误

### ISSUE THREAD

**Issue by shenchaobigdata** [hengxuZ/spot-trend-grid#3]
'''修改补仓止盈比率'''
        data_json = self._get_json_data()
        ratio_24hr = binan.get_ticker_24hour(symbol) #
        index = abs(ratio_24hr)

        if abs(ratio_24hr) >  8 : # 这是单边走势情况 只改变一方的比率
            if ratio_24hr > 0 : # 单边上涨，补仓比率不变

你好，作者，请问ratio_24hr返回的是什么数据结构，应该不是dict吧，abs会报错的，怎么能大于8，这个逻辑有问题吧，大于8就是单边行情吗？

**Comment by hengxuZ** [comment]
ratio_24hr 采用的24小时内波动比率。是int类型。如果返回的dict的话代表的是binan.get_ticker_24hour(symbol)接口报错。
